import logging
from typing import Optional, Dict, Any
from datetime import datetime

from github_service.manager import GitHubManager
from github.PullRequest import PullRequest
from github.Repository import Repository

logger = logging.getLogger(__name__)


class PRCreator:
    """Service for creating and managing pull requests."""
    
    def __init__(self, github_manager: GitHubManager):
        """
        Initialize PR creator.
        
        Args:
            github_manager: GitHubManager instance for API interactions
        """
        self.github_manager = github_manager
    
    def create_ci_pr(
        self,
        repo_name: str,
        yaml_content: str,
        release_branch: str,
        session_id: str
    ) -> Optional[Dict[str, Any]]:
        """
        Create a pull request with CI/CD workflow.
        
        Args:
            repo_name: Repository full name (owner/repo)
            yaml_content: Generated CI/CD YAML content
            release_branch: Target branch for the PR
            session_id: Session ID for reference
            
        Returns:
            Dictionary with PR details {number, url, html_url} or None if failed
        """
        try:
            # Get repository
            repo = self.github_manager.get_repo(repo_name)
            if not repo:
                logger.error(f"Repository not found: {repo_name}")
                return None
            
            # Verify target branch exists
            try:
                repo.get_branch(release_branch)
            except Exception as e:
                logger.error(f"Target branch '{release_branch}' does not exist: {e}")
                return None
            
            # Create feature branch
            feature_branch = f"devops-agent/ci-workflow-{session_id[:8]}"
            logger.info(f"Creating feature branch: {feature_branch}")
            
            if not self.github_manager.create_branch(repo, feature_branch, release_branch):
                logger.error(f"Failed to create feature branch: {feature_branch}")
                return None
            
            # Commit CI/CD file
            file_path = ".github/workflows/ci.yml"
            commit_message = f"ci: Add GitHub Actions CI/CD workflow (DevOps Agent)\n\nGenerated by DevOps Agent for automated CI/CD pipeline."
            
            logger.info(f"Committing {file_path} to {feature_branch}")
            if not self.github_manager.commit_file(
                repo=repo,
                file_path=file_path,
                file_content=yaml_content,
                commit_message=commit_message,
                branch=feature_branch
            ):
                logger.error(f"Failed to commit {file_path}")
                return None
            
            # Create pull request
            pr_title = "ci: Add GitHub Actions CI/CD workflow"
            pr_body = self._generate_pr_description(
                repo_name=repo_name,
                yaml_file=file_path,
                session_id=session_id
            )
            
            logger.info(f"Creating PR from {feature_branch} to {release_branch}")
            pr = self.github_manager.create_pull_request(
                repo=repo,
                title=pr_title,
                body=pr_body,
                head=feature_branch,
                base=release_branch
            )
            
            if not pr:
                logger.error("Failed to create pull request")
                return None
            
            logger.info(f"Created PR #{pr.number}: {pr.html_url}")
            
            return {
                "number": pr.number,
                "url": pr.url,
                "html_url": pr.html_url,
                "branch": feature_branch
            }
        
        except Exception as e:
            logger.error(f"Error creating PR: {e}")
            return None
    
    def get_pr_details(
        self,
        repo_name: str,
        pr_number: int
    ) -> Optional[Dict[str, Any]]:
        """
        Get pull request details and status.
        
        Args:
            repo_name: Repository full name
            pr_number: PR number
            
        Returns:
            Dictionary with PR details or None if not found
        """
        try:
            repo = self.github_manager.get_repo(repo_name)
            if not repo:
                return None
            
            pr = self.github_manager.get_pull_request(repo, pr_number)
            if not pr:
                return None
            
            return {
                "number": pr.number,
                "title": pr.title,
                "body": pr.body,
                "state": pr.state,
                "url": pr.html_url,
                "head_branch": pr.head.ref,
                "base_branch": pr.base.ref,
                "created_at": pr.created_at.isoformat() if pr.created_at else None,
                "updated_at": pr.updated_at.isoformat() if pr.updated_at else None,
                "merged": pr.merged,
                "merged_at": pr.merged_at.isoformat() if pr.merged_at else None,
                "mergeable": pr.mergeable,
                "review_comments": pr.review_comments,
                "comments": pr.comments,
            }
        
        except Exception as e:
            logger.error(f"Error getting PR details: {e}")
            return None
    
    def approve_pr(
        self,
        repo_name: str,
        pr_number: int,
        merge_method: str = "squash"
    ) -> bool:
        """
        Approve and merge a pull request.
        
        Args:
            repo_name: Repository full name
            pr_number: PR number to merge
            merge_method: Merge method (merge, squash, rebase)
            
        Returns:
            True if successful
        """
        try:
            repo = self.github_manager.get_repo(repo_name)
            if not repo:
                logger.error(f"Repository not found: {repo_name}")
                return False
            
            pr = self.github_manager.get_pull_request(repo, pr_number)
            if not pr:
                logger.error(f"PR #{pr_number} not found")
                return False
            
            if pr.state != "open":
                logger.warning(f"PR #{pr_number} is not open (state: {pr.state})")
                return False
            
            logger.info(f"Merging PR #{pr_number} using {merge_method} method")
            
            if self.github_manager.merge_pull_request(
                pr=pr,
                merge_method=merge_method
            ):
                logger.info(f"Successfully merged PR #{pr_number}")
                return True
            else:
                logger.error(f"Failed to merge PR #{pr_number}")
                return False
        
        except Exception as e:
            logger.error(f"Error approving PR: {e}")
            return False
    
    def get_diff_preview(
        self,
        repo_name: str,
        pr_number: int
    ) -> Optional[str]:
        """
        Get preview of file changes in PR.
        
        Args:
            repo_name: Repository full name
            pr_number: PR number
            
        Returns:
            Diff content or None
        """
        try:
            repo = self.github_manager.get_repo(repo_name)
            if not repo:
                return None
            
            pr = self.github_manager.get_pull_request(repo, pr_number)
            if not pr:
                return None
            
            # Get CI/CD file changes
            files = pr.get_files()
            diff_content = []
            
            for file in files:
                if ".github/workflows" in file.filename:
                    diff_content.append(f"File: {file.filename}")
                    diff_content.append(f"Status: {file.status}")
                    diff_content.append(f"Additions: {file.additions}")
                    diff_content.append(f"Deletions: {file.deletions}")
                    if file.patch:
                        diff_content.append("Diff:")
                        diff_content.append(file.patch[:500] + "..." if len(file.patch) > 500 else file.patch)
                    diff_content.append("---")
            
            return "\n".join(diff_content) if diff_content else "No CI/CD changes detected"
        
        except Exception as e:
            logger.error(f"Error getting diff preview: {e}")
            return None
    
    def _generate_pr_description(
        self,
        repo_name: str,
        yaml_file: str,
        session_id: str
    ) -> str:
        """
        Generate pull request description.
        
        Args:
            repo_name: Repository name
            yaml_file: Path to CI/CD file
            session_id: Session ID
            
        Returns:
            PR description text
        """
        description = f"""## DevOps Agent: GitHub Actions CI/CD Workflow

This pull request adds an automated CI/CD pipeline using GitHub Actions.

### What's Changed
- Added `{yaml_file}` with automated build, test, and deployment configuration

### Generated By
- **Tool**: DevOps Agent
- **Session**: {session_id}
- **Repository**: {repo_name}

### How to Review
1. Check the workflow file for accuracy
2. Verify build steps match your project requirements
3. Test the workflow by merging or running manually

### Next Steps
- [ ] Review the generated workflow
- [ ] Customize if needed
- [ ] Approve and merge to enable CI/CD

---
Generated by [DevOps Agent](https://github.com/yourusername/devops-agent)
"""
        return description
